### ISSUE TITLE
Correct multiplexing method for `chainHead_unstable_follow`

### ISSUE THREAD

**Issue by josepot** [smol-dot/smoldot#1067]
I'm looking to develop a browser extension that allows users to provide a valid chainspec and then returns an interface compliant with the [`chainHead` group of functions](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html#chainhead_unstable_follow) from the [latest JSON-RPC spec](https://paritytech.github.io/json-rpc-interface-spec).

Given:
1. We can detect if two different chainspecs are communicating with the [same chain](https://github.com/smol-dot/smoldot/blob/a47b9df3fc0aeeb603da25289d7b3eae9e0391fa/light-base/src/lib.rs#L629-L644).
2. The [`chainHead_unstable_follow`](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html#chainhead_unstable_follow) has a limit on the [maximum number of subscriptions](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html#multiple-subscriptions).

Previously, the `substrate-connect` extension multiplexed the instance returned by `addChain`. But this might not be the best approach with the current JSON-RPC spec due to the subscriptions limit.

**Question**:
Would the correct approach be to multiplex a `chainhead_unstable_follow` subscription per chain?

**Comment by tomaka** [comment]
In smoldot, whenever you add a chain, a "fresh new JSON-RPC server" is created, even if the chain is identical to a previously-added chain. Thanks to this, the limit is not shared between chains.

If your browser extension is using smoldot, just call `addChain` for every user.

**Comment by tomaka** [comment]
In general, the fact that smoldot de-duplicates chains should be considered as an implementation detail that has no influence whatsoever in any way on the behavior observed by API users or JSON-RPC clients.

**Comment by josepot** [comment]
This is awesome! Thank you for letting me know that!!

To ensure that we are on the same page: 

If 5 browser tabs are all connected to the same chain, the extension simply calls `addChain` for each tab, resulting in individual `Chain` instances for every tab. If 4 tabs are optimally unpinning blocks, while the 5th one isn't, then only the 5th tab’s `Chain` subscription would trigger the `stop` event. The other 4 tabs would continue to function unaffected by the behavior of the 5th tab.

Is my interpretation accurate?

**Comment by tomaka** [comment]
Yes, and if not it's a bug in the code
