### ISSUE TITLE
Handle log level and target

### ISSUE THREAD

**Issue by xlc** [smol-dot/smoldot#1244]
https://github.com/smol-dot/smoldot/blob/4faf2c043d31d3b814597dea8e95ba78e4a8b2dc/lib/src/executor/host.rs#L3438

I would love to have those to help with the log monitoring. For example, I want to trigger an alert for any logs with error level.

That also means this can't be a simple string, but a vector of some Log item

https://github.com/smol-dot/smoldot/blob/4faf2c043d31d3b814597dea8e95ba78e4a8b2dc/lib/src/executor/runtime_host.rs#L1230-L1231

**Comment by tomaka** [comment]
> That also means this can't be a simple string, but a vector of some Log item

I would just generate an event for every log host function that's being called, like in `host.rs`
