### ISSUE TITLE
Plans for next release?

### ISSUE THREAD

**Issue by lexnv** [smol-dot/smoldot#1274]
First of all, thanks a lot for the help with https://github.com/smol-dot/smoldot/pull/1250 and the work towards simplifying the `PlatformRef`.

I was wondering if there are any plans to release smoldot soon, since we could use the latest updates in suxbt, although it is not urgent, thanks! 🙏

**Comment by tomaka** [comment]
I have recently merged #1200, which is a big refactor and has had a bit of a downfall (#1246, #1247, #1248, #1249). I will publish a version once these are (mostly) resolved.
