### ISSUE TITLE
panicked at 'assertion failed: !(-32700..=-32000).contains(&n)', lib/src/json_rpc/parse.rs:292:13

### ISSUE THREAD

**Issue by kratico** [smol-dot/smoldot#1391]
Attached [logs](https://github.com/smol-dot/smoldot/files/13439578/emeglniefffeegmbhkldcfgjopgalnpo-1700658019785.log)

Perhaps the issue is related to the warning before the panic

```
[json-rpc-polkadot] Rejected `chainHead_unstable_follow` subscription due to limit reached.
```

<img width="543" alt="image" src="https://github.com/smol-dot/smoldot/assets/1209171/fdc1bf52-b15a-45fd-8aaf-4adc67429711">

Note: this is using `smoldot@2.0.10`

**Comment by tomaka** [comment]
The error turns out to be legitimate: https://github.com/paritytech/json-rpc-interface-spec/pull/115
