### ISSUE TITLE
sleep recovery issues

### ISSUE THREAD

**Issue by josepot** [smol-dot/smoldot#1458]
I'm currently working on a dApp using Polkadot API, which leverages smoldot through the new JSON-RPC API. The application functions as expected, but I've encountered a peculiar issue related to how the smoldot process, running on the service-worker of the substrate-connect extension, behaves after waking up from an extended period of inactivity (e.g., laptop sleep mode).

**Observed Behavior:**

- **Initial Wake-Up Phase:**
  - When the smoldot process resumes after a period of inactivity (e.g., a few hours), it successfully allows its consumers to add new chains and to stablish the [`chainHead_unstable_follow`](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_follow.html#chainhead_unstable_follow) subscription (with the `withRuntime` parameter set to `true`).
  - However, smoldot immediately triggers an `initialized` event, referencing a significantly outdated block.

- **Issues During Catch-Up:**
  - Attempting operations on this outdated block results in an `operationInaccessible` event.
  - Meanwhile, the `chainHead_unstable_follow` subscription rapidly produces blocks, attempting to catch up to the current finalized block.

- **Catch-Up Duration:**
  - The catch-up process takes approximately a 2-3 minutes for an 8 hour offline period.

- **Comparison with a New Instance:**
  - Starting a fresh instance of smoldot leads to an almost immediate synchronization, in contrast to the prolonged "catch-up" time.

**Potential Workaround:**
- A possible solution on our end could be to restart the smoldot process after detecting extended inactivity. However, I'm curious if there's a better solution.

**Comment by josepot** [comment]
I guess that I never stated what IMO should be the ideal behaviour:

- smoldot should emit the `stop` event to any "stale" `chainHead_unstable_followsubscriptions` that were created before the device went to sleep.
- new `chainHead_unstable_follow` subscriptions should not receive the `initialized` event until smoldot has actually finished synchronizing.

It seems to me that the issue has to do with the fact that smoldot tries to keep the stale `chainHead_ustable_follow` subscriptions "alive" after it recovers from a time of inactivity.

**Comment by josepot** [comment]
I created the [following repo](https://github.com/josepot/smoldot-sleep-recovery) in order to "easily" test the issue and capture some logs. These are some logs that I captured running [this code](https://github.com/josepot/smoldot-sleep-recovery/blob/f7fee42f1c95dbc690b49b1603a1277a1c362b30/src/main.ts).

[smoldot-logs.txt](https://github.com/smol-dot/smoldot/files/13629562/smoldot-logs.txt): the logs of the smoldot process.
[main-logs.txt](https://github.com/smol-dot/smoldot/files/13629563/main-logs.txt): the output of the program.

While the program was running I put my computer to sleep on 3 occasions:
- After `2023-12-10T22:38:48.534Z` for ~1 minute.
- After `2023-12-10T22:40:48.243Z` for ~2 minutes.
- After `2023-12-10T22:44:54.354Z` for ~3 minutes.

Smoldot never recovered from the last one.

**Comment by tomaka** [comment]
> The catch-up process takes approximately a 2-3 minutes for an 8 hour offline period.

This will be solved by https://github.com/smol-dot/smoldot/issues/1109

> Smoldot never recovered from the last one.

Yeah there seems to be an issue where ping timeouts aren't detected or don't lead to the connection being killed. For this reason, smoldot still thinks it's connected to 4 peers.
For what it's worth, smoldot should actually recover after an hour or so due to the operating system killing the dead connection.

**Comment by tomaka** [comment]
Closing in favor of https://github.com/smol-dot/smoldot/issues/1109
