### ISSUE TITLE
smoldot@2.0.14 odd behaviours

### ISSUE THREAD

**Issue by josepot** [smol-dot/smoldot#1468]
I have been trying the latest version (2.0.14) of smoldot and I have observed 3 different behaviours:

1) Everything works perfectly well
2) It gets completely stuck during the warp sync process
3) The warp sync process takes a while to complete, and once it completes the "initialized" event gets emitted, but no other events follow after that.

I was able to capture the detailed smoldot logs of the 3rd case using the code from [this repo](https://github.com/josepot/smoldot-sleep-recovery). The logs:
- [smoldot-logs.txt](https://github.com/smol-dot/smoldot/files/13648042/smoldot-logs.txt)
What the program produced:

```txt
2023-12-12T12:21:08.880Z - starting new chainHead follow subscription
2023-12-12T12:21:31.749Z - Initialized - 0x4ab0663d9dc0247e519d767c4232dd5cefb88049f72457ad628eb3f41c532614
```

It took more than 20 seconds for the `initialized` event to arrive, when most of the times it takes ~2 seconds, and then no other events came afterwords (I waited > 1 minute).

I will try to capture more logs and I will be posting them in this issue.

**Comment by tomaka** [comment]
The node repeatedly tries to send a warp sync request to `12D3KooWS9ZcvRxyzrSf6p63QfTCWs12nLoNKhGux865crgxVA4H`, who repeatedly denies it.

**Comment by tomaka** [comment]
I forgot to mention it, but it would be fixed by https://github.com/smol-dot/smoldot/issues/1442

**Comment by tomaka** [comment]
Closing in favor of https://github.com/smol-dot/smoldot/issues/1442
