### ISSUE TITLE
`transaction_unstable_submitAndWatch` gets stuck on `broadcasted` event

### ISSUE THREAD

**Issue by josepot** [smol-dot/smoldot#1596]
I've experienced this problem a few times, but it's not easy to reproduce. This time, however, I was able to get the logs from the `@substrate/connect` extension. I hope that the logs are helpful.

What I experience is that smoldot seems to get stuck on the `broadcasted` event after having submitted a transaction over `transaction_unstable_submitAndWatch` (the transaction was [successfully included](https://polkadot.statescan.io/#/extrinsics/19142960-2) into the blockchain, though):

![image](https://github.com/smol-dot/smoldot/assets/8620144/24c7f39a-2789-4a8f-9f63-0cec19f478cf)

The logs:
[console-1705869526874.log](https://github.com/smol-dot/smoldot/files/14002771/console-1705869526874.log)

**Comment by tomaka** [comment]
The logs were taking too late or something and don't include the block in which the transaction was included.
