### ISSUE TITLE
JSON-RPC error 

### ISSUE THREAD

**Issue by rllola** [smol-dot/smoldot#1616]
I am trying to call the a rpc endpoint but I keep getting an error.

```
$ curl http://127.0.0.1:9944/ \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"rpc_methods","params":[],"id":1,"jsonrpc":"2.0"}'
curl: (52) Empty reply from server
```

In the logs I can see
```
[2024-01-26T13:04:20.745Z] [debug] json-rpc-incoming-connection; address=127.0.0.1:46314
[2024-01-26T13:04:20.745Z] [debug] json-rpc-connection-error; address=127.0.0.1:46314, error=handshake was not a GET request
```

Not sure why.

**Comment by tomaka** [comment]
The server expects a WebSocket connection, not just plain HTTP requests.

In general, many JSON-RPC functions don't make sense to call over HTTP requests anyway, so doing JSON-RPC calls through HTTP is kind of a deprecated mechanism.
