### ISSUE TITLE
Implement support for child tries

### ISSUE THREAD

**Issue by tomaka** [smol-dot/smoldot#166]

**Comment by tomaka** [comment]
The next step in adding support would be to update [`runtime_host.rs`](https://github.com/smol-dot/smoldot/blob/a9c9e5b590b4e2f783ce404221d8604ab8efc2c0/lib/src/executor/runtime_host.rs#L84).

This basically contains the logic of the pending changes that have been made by the storage but not saved yet.
It also contains the logic of "transactions", where the runtime can start a transaction and then later potentially revert it.

Adding support for child tries in an efficient way (I'm not looking for the most optimal implementation, but at least the best possible `O`-notation complexity) seems extremely complicated, although I haven't precisely looked into it yet.

**Comment by cmichi** [comment]
@tomaka Would you be open to writing out a W3F grant for someone to implement this?

For context: We need this not only for using light clients with smart contract Dapps, but also for some more advanced testing tooling and some features that auditors of ink! contracts requested.

**Comment by tomaka** [comment]
Writing a grant would probably take me way more time than doing it myself

**Comment by cmichi** [comment]
I was honestly hoping for this response 😜 .

**Comment by cmichi** [comment]
So do you think there's a chance of implementing it some time in the next weeks?

**Comment by tomaka** [comment]
Honestly the biggest obstacle is that the way child tries work is a bit of an illogical shit show, and I have the biggest trouble in the world finding someone who is able to explain me how they work in Substrate.

**Comment by tomaka** [comment]
https://github.com/smol-dot/smoldot/issues/272 should to be tackled first in order to avoid having to maintain a cache of each child tries. Removing the caches would considerably simplify the implementation.
An alternative could be to just not have a cache, but that would not be a long term solution. Having no cache first would just make #272 more difficult to do.

**Comment by tomaka** [comment]
I've noticed a bunch of people follow this issue, so to keep you updated:
#639 was a major change blocking this. Now that it has landed, it should be possible to add proper support for child tries in `runtime_host.rs`.

**Comment by tomaka** [comment]
If someone is willing to help, having test cases would be extremely appreciated. Since I'm unfamiliar with runtime development and Substrate APIs in general, just creating a contracts chain would probably take me ten times the time necessary to implement the feature. And given that the way child tries work is very poorly documented, these test cases would be extremely useful.

Ideally, I would need as test fixture the header and body of a block that uses child tries in some way (e.g. creating, executing, or deleting a contract) plus the storage of its parent. If the parent is the genesis block, then the storage can be in the chain spec.

**Comment by tomaka** [comment]
Remains to do:

- [ ] Accept proofs that contain child tries. Right now they'd be rejected because they contain unused entries.
- [ ] Add a child tries diff system to `runtime_host.rs`.
- [ ] Adjust the public APIs of `StorageGet`/`NextKey`/`ClosestDescendantMerkleValue` to indicate from which trie to read from.

**Comment by cmichi** [comment]
> If someone is willing to help, having test cases would be extremely appreciated. Since I'm unfamiliar with runtime development and Substrate APIs in general, just creating a contracts chain would probably take me ten times the time necessary to implement the feature. And given that the way child tries work is very poorly documented, these test cases would be extremely useful.
> 
> Ideally, I would need as test fixture the header and body of a block that uses child tries in some way (e.g. creating, executing, or deleting a contract) plus the storage of its parent. If the parent is the genesis block, then the storage can be in the chain spec.

@pgherveou Could you help here? The overall context for this issue is that it's needed to enable light client support of `pallet-contracts`.

**Comment by pgherveou** [comment]
@tomaka looking into your request, if you want to give me more info happy to jump on an [element](@pg:parity.io) / [google meet call](pgherveou@parity.io)

**Comment by pgherveou** [comment]
following up here, 
We have test cases in `pallet-contracts` that does things that are similar to what you described above, for example in this `lazy_removal` tests, we compile a basic contract from a .wat file, put some data in it's child_trie storage and check if things works as expected upon termination.

https://github.com/paritytech/substrate/blob/55bb6298e74d86be12732fd0f120185ee8fbfe97/frame/contracts/src/tests.rs#L2337-L2415

These tests relies on `sp_io::TestExternalities` (see https://docs.substrate.io/test/unit-testing/#test-storage-in-a-mock-runtime) to test storage in a mock environment.

With this context, let me know whether or not we could adapt  a similar setup  in smol-dot to provide the test cases that you mentioned above.

**Comment by tomaka** [comment]
Hi,

I have zero knowledge or motivation to figure out how Substrate's API works.
What I'm looking for is raw data plus a written (non-code) explanation of what this data is.

One way could be to dump the entire content of the storage of block N, plus the header and body of block N+1. This is only useful of block N+1 modifies child tries in some way, preferably in the most interesting way possible (such as creating or deleting one).

**Comment by tomaka** [comment]
After https://github.com/smol-dot/smoldot/pull/684, child tries support is supposed to work. In other words, if I was sure that the code didn't contain any bug, I would close this issue as there's nothing left to do.
However, given that everything was implemented through guesswork, I'll keep this issue open before there's reasonable confidence that things work.

**Comment by tomaka** [comment]
I've opened https://github.com/w3f/polkadot-spec/issues/648 for what it's worth.

**Comment by pgherveou** [comment]
Ok got it, I could try to run these tests in a "real" environment and export the raw storage.
Is there any specific DB backend or data format export I should use so that it can be consumed in your tests?

**Comment by tomaka** [comment]
For the format, please not a RocksDB/ParityDB database file, as I can't open that without digging through the internals of Substrate. Just JSON or whatever. I can always re-convert myself.
If the test creates a new chain from scratch (I assume it does), then exporting the chain specification works, as it contains the storage of block 0.

Another way to create a test, which I could do myself, could be to ask for a call proof for `Core_execute_block` with a block that uses child tries. The test would be more messy, but in terms of coverage it would be similar.

**Comment by pgherveou** [comment]
Ok here what I can do easily
Let me know if that would fit your needs, and I will get to it:

- use https://github.com/paritytech/substrate-contracts. This node is configured with `pallet-contracts` and also uses the 
`manual-seal` consensus where blocks are authored at every transaction.
- upload a dummy smart contract that adds or remove data from it's child trie storage
- create and run a simple rust script to export rocksdb keys and values to JSON, I can export before and after running the contract call transactions
- use the node export-blocks command to export the relevant blocks

**Comment by tomaka** [comment]
That could work!

> create and run a simple rust script to export rocksdb keys and values to JSON, I can export before and after running the contract call transaction

I specifically need the storage values of the trie, not the key-values that RocksDB contains. Substrate unfortunately has dozens of incomprehensible layers of abstraction between the trie and RocksDB.

This needs to be for the block that touches contracts is authored.

> use the node export-blocks command to export the relevant blocks

I'm not sure in which format the blocks are going to be. I'm afraid that it might also export some opaque data structure that can only be deciphered by looking deep inside the internals of Substrate. But I'm not sure of what I'm saying here.

**Comment by pgherveou** [comment]
> I specifically need the storage values of the trie, not the key-values that RocksDB contains. Substrate unfortunately has dozens of incomprehensible layers of abstraction between the trie and RocksDB.

I can probably find out what are the relevant keys, maybe by diffing and filtering the new entries.  You would need all the key and values for the path and the actual values stored right?

**Comment by tomaka** [comment]
> testing the exports block command, instantiating a dummy flipper contract does the following this is the JSON that I get:
> 
> ```json
> {
>   "block": {
>     "header": {
>       "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
>       "number": "0x0",
>       "stateRoot": "0xd7a3ce9f2563d88e75baa2efe0a247e07e4e048e65543de49ed4ce36a615fe80",
>       "extrinsicsRoot": "0x03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c111314",
>       "digest": {
>         "logs": []
>       }
>     },
>     "extrinsics": []
>   },
>   "justifications": null
> }
> {
>   "block": {
>     "header": {
>       "parentHash": "0x2aa8db7e12a525e68f43484ec634ad9254cf4133ba947c7748f11b69216cc62b",
>       "number": "0x1",
>       "stateRoot": "0x2da0f668c29f006d3a69fecc771f5ee88ff466df8d4f314c00bd6634da53c2bc",
>       "extrinsicsRoot": "0x7a2327f12e4a5a4c8929e098036346570e43ff82e9902782f94545efacdc8700",
>       "digest": {
>         "logs": []
>       }
>     },
>     "extrinsics": [
>       "0x280403000b1011fe998801",
>       "0x01198400d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d013c4d5831f171022ea3ed5f8158807b510b81d39b6438eeb13255932d023a132ec79c4e08dd8af41436c531db3757087bc746ecbdb90ae4d906e54bd75209ad820b00000008070072e23c21c6040100010780edff7d78ed150061736d0100000001240760027f7f0060000060047f7f7f7f017f60037f7f7f006000017f60017f017f60017f00027406057365616c310b6765745f73746f726167650002057365616c301176616c75655f7472616e736665727265640000057365616c3005696e7075740000057365616c320b7365745f73746f726167650002057365616c300b7365616c5f72657475726e000303656e76066d656d6f727902010210030b0a000304050001060001010608017f01418080040b0711020463616c6c000d066465706c6f79000e0aaa090a2601017f230041106b22022400200220003a000f20012002410f6a41011006200241106a24000b6f01037f024002402000280208220320026a22042003490d00200420002802044b0d00200420036b2002470d01200028020020036a210541002103037f2002200346047f200505200320056a200120036a2d00003a0000200341016a21030c010b0b1a200020043602080f0b000b000b5502027f027e230041206b22002400200041106a22014200370300200042003703082000411036021c200041086a2000411c6a10012001290300210220002903082103200041206a2400410541042002200384501b0b3f01017f2000280204220145044041020f0b2000200141016b36020420002000280200220041016a3602004101410220002d000022004101461b410020001b0b29002000027f20014504404180800441003a000041010c010b418080044181023b010041020b100c000b12004180800441003b010041004102100c000b990101047f230041206b220124002001428080013702142001418080043602102001410036020c200141106a2001410c6a4104100602402001280214220420012802182202490d0020012802102103200141003602182001200420026b3602142001200220036a3602102000200141106a10052001280218220020012802144b0d00200320022001280210200010031a200141206a24000f0b000b0d0020004180800420011004000ba20301057f230041106b22002400024002400240100741ff01714105470d00200041808001360200418080042000100220002802002201418180014f0d0020014104490d02418080042802002201411876210220014110762104200141087621030240200141ff0171220141e3004704402001412f47200341ff01714186014772200441ff017141db0047720d0441002104200241d901460d010c040b200341ff0171413a47200441ff017141a50147720d0341012104200241d100470d030b2000428080013702042000418080043602002000410036020c20002000410c6a410410062000280204220320002802082201490d00200028020021022000200320016b220336020020022001200120026a22012000100020032000280200220249720d0020002002360204200020013602002000100841ff017122014102460d002004450d01200145100b410041001009000b000b230041106b220024002000418080043602004180800441003a0000200042808081801037020420014100472000100520002802082200418180014f0440000b41002000100c000b410141011009000bf00101057f230041106b2200240002400240100741ff01714105470d0020004180800136020c418080042000410c6a1002200028020c2201418180014f0d00024020014104490d002000418480043602002000200141046b36020441808004280200220141187621022001411076210320014108762104200141ff0171220141ed014704402001419b0147200441ff017141ae014772200341ff0171419d0147200241de004772720d012000100841ff017122004102460d012000100b100a000b200441ff017141cb0047200341ff0171419d0147720d002002411b460d020b410141011009000b000b4100100b100a000b149bae9d5e010901307866303737313362316431326339646335363163366436646363653635363532653538333466323166663932313835386263333566333734623432353837303437"
>     ]
>   },
>   "justifications": null
> }
> ```

It's a bit of an annoying format, but I can do with that with some manual conversions

> I can probably find out what are the relevant keys, maybe by diffing and filtering the new entries. You would need all the key and values for the path and the actual values stored right?

I don't need the new entries, I need the old entries. I need the values *before* the block.
Specifically I need the values that are read by the block (including branch nodes), but since it's hard for you to know which values are read and which aren't, we'll do have to do with all values.

**Comment by pgherveou** [comment]
> It's a bit of an annoying format, but I can do with that with some manual conversions
There is also a binary format, but I assumed that it would not be helpful in this context

> I don't need the new entries, I need the old entries. I need the values before the block.
Specifically I need the values that are read by the block (including branch nodes), but since it's hard for you to know which values are read and which aren't, we'll do have to do with all values.

That would be in the POV if this was a parachain in Polkadot right, let me see if I can try to figure this out.

**Comment by pgherveou** [comment]
I guess the easier would be to only call the contract in the block vs uploading and instantiating it, that should reduce the number of keys that are read. The call would only read and update a storage key that are stored in the contract child trie.

**Comment by tomaka** [comment]
> That would be in the POV if this was a parachain in Polkadot right, let me see if I can try to figure this out.

That would give a more complicated and less isolated test because I have to decode the proof and all.
As I've mentioned above, I can ask for POVs by sending a request to a node, I don't really need your help for that.

**Comment by pgherveou** [comment]
Until I find a more user friendly way to share this:
Here is what I did and the output:
I ran `substrate-contracts-node` , and uploaded and instantiated a simple smart contract that set a String in storage.
The zip contains the rocksdb export of the chain at block 0 and 1, and the json block exports

[block_and_states.zip](https://github.com/smol-dot/smoldot/files/11687374/block_and_states.zip)

**Comment by pgherveou** [comment]
There are a few keys that are added in block 1, they correspond to the new accounts that are created by the contract, and the various storage that are created for managing the contract and it's storage,  if that helps I can give you names for all of these keys

**Comment by tomaka** [comment]
Ah thanks, that looks promising!
However I don't understand why the runtime code is not stored at `:code` (`0x3a636f6465`), like it's always supposed to be, but instead at `0x3a636f646532b090ba46cc0bac21ab1b180c4f1649242c7a7db2b199881880a8a6d4466ad9`
Is it a particularity of the contracts chain?

**Comment by pgherveou** [comment]
mm good point, I think this last  key is the code of the wasm contract not the runtime.
First time, I am digging into the guts of substrate, let me double check these values as well and get back to you.

Also Basti told me about these APIs that might also give us similar informations,
https://paritytech.github.io/substrate/master/sc_rpc_api/state/trait.StateApiClient.html#method.trace_block

**Comment by pgherveou** [comment]
I do this the runtime code under (`0x3a636f6465`) when I query it from polkadot.js
there might be something missing from my naive db extract here : https://github.com/pgherveou/rocksdb_export_json/blob/main/src/main.rs

**Comment by pgherveou** [comment]
actually this is in the JSON under `3a636f646532b090ba46cc0bac21ab1b180c4f1649242c7a7db2b199881880a8a6d4466ad9` not sure why it's not just `3a636f6465`

**Comment by pgherveou** [comment]
sorry that's exactly what you said above haha

**Comment by pgherveou** [comment]
fyi this is the storage hash
<img width="1189" alt="Screenshot 2023-06-08 at 17 28 22" src="https://github.com/smol-dot/smoldot/assets/521091/fb5784b7-57f7-4293-a193-2eb983471ce2">

What would be the next steps to make these dataset useful for your test cases?

**Comment by pgherveou** [comment]
I think only the leaves keys have the storage hash.
also as it is exported now, the db hold the previous and current keys, (ie old value are not pruned)
What would be the ideal export state for you to make this useful?

**Comment by pgherveou** [comment]
I am just trying to help here, for me "simplest" is giving you the raw output that I get from substrate, I understand that smoldot is working without the same abstraction, that's why I am asking what format works best for you.

**Comment by tomaka** [comment]
What I mean by "simplest" is "simple" in terms of purity, not what is simple for you to generate. For example just a value is more simple than a value plus its hash concatenated together. I am generally frustrated by Substrate being over-engineered and not being able to generate simple things.

**Comment by pgherveou** [comment]
Ok looked into it a bit more this pm
It turned out that trying to dump the db as JSON was indeed not the best approach.
Luckily, Frame exposes some handy rpc state endpoints to get the raw data:
- https://paritytech.github.io/substrate/master/sc_rpc_api/state/trait.StateApiClient.html#method.storage_keys
- https://paritytech.github.io/substrate/master/sc_rpc_api/state/trait.StateApiClient.html#method.storage
- https://paritytech.github.io/substrate/master/sc_rpc_api/state/trait.StateApiClient.html#method.query_storage 

combining these into a [small cli](https://github.com/pgherveou/contracts-query/tree/main) 
I was able to export the db and the storage change set for each block 

[Archive.zip](https://github.com/smol-dot/smoldot/files/11709929/Archive.zip)

**Comment by tomaka** [comment]
Thanks! cc https://github.com/smol-dot/smoldot/pull/722

There are a few changes to make:

- I need the database of block 0, not of block 1. So https://github.com/pgherveou/contracts-query/blob/630ad7d87dc718846226e92800d61f4e4e618064/src/main.rs#LL31C34-L31C38 and https://github.com/pgherveou/contracts-query/blob/630ad7d87dc718846226e92800d61f4e4e618064/src/main.rs#LL42C54-L42C58 need to be the hash of block 0 rather than `None`

- Don't use `getKeysPaged` (https://github.com/pgherveou/contracts-query/blob/630ad7d87dc718846226e92800d61f4e4e618064/src/main.rs#L133) but `getKeys`. Right now you're getting only the first 100 keys, and not all of them.

I'm also using the block 1 from your comment a few days ago, is it still the same? I suggest that your script also retrieves block 1 so that we're sure that they correspond.

**Comment by tomaka** [comment]
:+1: There's absolutely no rush, by the way

**Comment by pgherveou** [comment]
Here you go: [Archive.zip](https://github.com/smol-dot/smoldot/files/11720070/Archive.zip)
database is exported at block 0
added block 1 in blocks.json

source if you want to check it https://github.com/pgherveou/contracts-query/blob/404079d270cd7c7e4ae98e4eb42ac49996af1634/src/main.rs#L50-L93

**Comment by tomaka** [comment]
Thanks

The test is failing but in a way that lets me think there's a bug in smoldot.

Interestingly, the runtime doesn't call `ext_default_child_storage_root` like I thought it was supposed to do. This means that answer to [question 9](https://github.com/w3f/polkadot-spec/issues/648) is probably `Some`, and `runtime_host.rs` needs to manually commit the child trie root change to the main trie.

**Comment by tomaka** [comment]
The test is now passing after https://github.com/smol-dot/smoldot/pull/743

Would it also be possible to generate three other test cases :pray: 

- One that creates two contracts in the same block, so that I test if multiple child tries at the same time work
- One that accesses/calls a contract that already existed in the previous block.
- One that destroys a contract that already existed in the previous block.

For the last two, you probably also have to do something like create a contract in block 1, then access/destroy it in block 2. In that case I need the storage of block 1. That storage must also include the child tries of the block, instead of only the main trie. It's unfortunately not really clear to me how to do that.

**Comment by pgherveou** [comment]
> That storage must also include the child tries of the block, instead of only the main trie. It's unfortunately not really clear to me how to do that.

don't the storage APIs mentioned above returned all storage keys, whether they are child trie keys or or not 🤔

**Comment by pgherveou** [comment]
Added all of this in the repo https://github.com/pgherveou/contracts-query/tree/main
it's all generated by this script (https://github.com/pgherveou/contracts-query/blob/main/export.sh)
- block 1 -> instantiate contract
- block 2 -> instantiate contract x 2 (using same code but instantiating it twice)
- block 3 -> call contract created at block 1
- block 4 -> call contract terminate 

db is exported at each block and all blocks are exported in blocks.json

**Comment by tomaka** [comment]
The way child tries work is that every key that starts with `0x3a6368696c645f73746f726167653a64656661756c743a` contains a value that corresponds to a child trie. And I would need their content :pray: 
I think you can retrieve the content of these child tries using `childstate_getKeys`, `childstate_getStorage` and similar.

So for example when looking at `db-3.json`, there's this:
```json
{
    "key": "0x3a6368696c645f73746f726167653a64656661756c743a14e6ea499ccfe3241adbcf937cfb9d41cb1c33d4c33e5bbf72deb7701a286d53",
    "value": "0xedafed99882fa0a681b7d285180098a9fa0b757bcc2ff51a249c88a80f698079"
  },
  {
    "key": "0x3a6368696c645f73746f726167653a64656661756c743a9c32e5ae59a1f5bc78d625dedc7bce6e788152dee2a0b77837c3cd2e7c7ce1ed",
    "value": "0x233859be5ca485b609b339f61deb9104c9918c91f48dc78f3bc9f858cb304ad3"
  },
  {
    "key": "0x3a6368696c645f73746f726167653a64656661756c743aeb412d2bf2f48d26267fe76b4b9854cf31038b2b465e4ba845b264f4559ba5f6",
    "value": "0xedafed99882fa0a681b7d285180098a9fa0b757bcc2ff51a249c88a80f698079"
  },
```

Meaning that there are 3 child tries identified by `0xedafed99882fa0a681b7d285180098a9fa0b757bcc2ff51a249c88a80f698079`, `0x233859be5ca485b609b339f61deb9104c9918c91f48dc78f3bc9f858cb304ad3`, and `0xedafed99882fa0a681b7d285180098a9fa0b757bcc2ff51a249c88a80f698079`.
These are the values that you would need to pass as the first parameter of `childstate_getKeys` or `childstate_getStorage`

**Comment by pgherveou** [comment]
Ok out of curiosity this `0x3a6368696c645f73746f726167653a64656661756c743a` is this something hard coded somewhere or it's just specific to our small dataset here ?

**Comment by pgherveou** [comment]
so to be clear, you would like to fill the missing key, values in the db-x.json files to take into account all storage keys including the child-state keys that are currently missing

**Comment by tomaka** [comment]
`0x3a6368696c645f73746f726167653a64656661756c743a` is hardcoded. It's ASCII for `:child_storage:default:`

> so to be clear, you would like to fill the missing key, values in the db-x.json files to take into account all storage keys including the child-state keys that are currently missing

Yes!

You can for example add a new map that looks something like this:

```json
"child_tries": {
    "14e6ea499ccfe3241adbcf937cfb9d41cb1c33d4c33e5bbf72deb7701a286d53": [
        {"key": ..., "value", ...},
        {"key": ..., "value", ...}
    ],
    "9c32e5ae59a1f5bc78d625dedc7bce6e788152dee2a0b77837c3cd2e7c7ce1ed": [
        {"key": ..., "value", ...},
        {"key": ..., "value", ...}
    ],
    ...
}
```

**Comment by pgherveou** [comment]
updated the files in the repo with the child_keys
format is 
```json
  "child_tries": {
    "0x3a6368696c645f73746f726167653a64656661756c743aeb412d2bf2f48d26267fe76b4b9854cf31038b2b465e4ba845b264f4559ba5f6": [
      [
        "0x11d2df4e979aa105cf552e9544ebd2b500000000",
        "0x38466972737420636f6e7472616374"
      ]
    ],
    "0x3a6368696c645f73746f726167653a64656661756c743a14e6ea499ccfe3241adbcf937cfb9d41cb1c33d4c33e5bbf72deb7701a286d53": [
      [
        "0x11d2df4e979aa105cf552e9544ebd2b500000000",
        "0x38466972737420636f6e7472616374"
      ]
    ]
  }
```
the outer keys have the suffix and  (key, values) are encoded as an array of 2 instead of an object, if this is inconvenient to consume we can map it to the suggested format.

**Comment by pgherveou** [comment]
actually pushed another commit with { key, value } object

**Comment by tomaka** [comment]
> if this is inconvenient to consume we can map it to the suggested format.

Once we're happy with the tests I'll do some conversion to something a bit better

**Comment by tomaka** [comment]
Ok, with https://github.com/smol-dot/smoldot/pull/763 all the tests are passing! Thanks for the help.

I think that there's reasonable confidence that smoldot supports child tries. There are probably issues in corner cases, but none of which can be reached through the paths that a runtime would normally take.
