### ISSUE TITLE
panicked at /__w/smoldot/smoldot/lib/src/chain/blocks_tree.rs:333:72: called `Result::unwrap()` on an `Err` value: NonLinearBabeEpochs

### ISSUE THREAD

**Issue by kratico** [smol-dot/smoldot#1691]
Using `smoldot@2.0.21`, Smoldot has panicked while executing task `sync-service-rococo_v2_2`

```
panicked at /__w/smoldot/smoldot/lib/src/chain/blocks_tree.rs:333:72:
called `Result::unwrap()` on an `Err` value: NonLinearBabeEpochs
```

Attached [logs](https://github.com/smol-dot/smoldot/files/14420149/console-1709040399168.log)

**Comment by DragonDev1906** [comment]
I've had the same panic when trying to persist the `NonFinalizedTree`, see #1689, which might have the same cause.
