### ISSUE TITLE
`state_getKeysPaged` Returns wrong key

### ISSUE THREAD

**Issue by NachoPal** [smol-dot/smoldot#1708]
I am using `smoldot` `0.17.0`.

It returns a wrong key when there is only a single key under the queried prefix.

To give an example:

Request (`hrmp.hrmpEgressChannelsIndex` key)
```js
{
      "id": 61,
      "jsonrpc": "2.0",
      "method": "state_getKeysPaged",
      "params": [
        "0x6a0da05ca59913bc38a8630590f2627cf12b746dcf32e843354583c9702cc020",
        1000,
        "0x6a0da05ca59913bc38a8630590f2627cf12b746dcf32e843354583c9702cc020"
      ]
}
```
Result:
```js
{
    result: [
       // Expected single key
      "0x6a0da05ca59913bc38a8630590f2627c…702cc020b6ff6f7d467b87a9e8030000",
       // Unexpected key -> paraScheduler.validatorGroups
      "0x94eadf0156a8ad5156507773d0471e4a16973e1142f5bd30d9464076794007db"
    ]
}    
```

It works though if there are more than one keys under the queried prefix

**Comment by josepot** [comment]
> I am using `smoldot` `0.17.0`.

is this a typo? 🤔 The current version is `2.0.22`

**Comment by NachoPal** [comment]
> is this a typo? 🤔 The current version is 2.0.22

it refers to the `smoldot` crate version

**Comment by tomaka** [comment]
On which chain does this happen? This would be useful for me to debug the issue more easily. All the chains I try have more than one key.

**Comment by tomaka** [comment]
I can't fix this issue without knowing how to reproduce it.

**Comment by tomaka** [comment]
Closing as OP is non-responsive and there's nothing I can do. Please reopen if you come back.
