### ISSUE TITLE
Error in runtime spec Wasm sections: RuntimeVersionDecode

### ISSUE THREAD

**Issue by lrazovic** [smol-dot/smoldot#1711]
Hey, I encounter a problem when starting the demo and/or forking the Polimec chain using Chopsticks. The error is as follows:

```
Failed to compile runtime. Size of `:code`: 1.2 MiB.
Error: Error in runtime spec Wasm sections: RuntimeVersionDecode
This indicates an incompatibility between smoldot and the chain.
```

How to reproduce:
+ `$ cd demo-chain-specs/ && wget https://raw.githubusercontent.com/Polimec/polimec-node/main/chain-specs/polimec-raw-chain-spec.json`.
+ Add the downloaded chain spec to the `chainSpecsFiles` array in the `wasm-node/javascript/demo/demo.mjs` file. e.g.
```js
const chainSpecsFiles = [
    '../../demo-chain-specs/polkadot.json',
    '../../demo-chain-specs/polimec-raw-chain-spec.json',
];
```
+ Run `$ npm run start` in the `wasm-node/javascript/demo` folder.
+ Open `https://cloudflare-ipfs.com/ipns/dotapps.io/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fpolimec-base`.

The runtime is available here: https://github.com/Polimec/polimec-node/blob/main/runtimes/base/src/lib.rs. 

Do we have to change anything in the Polimec runtime to make it compatible with Smoldot? 

Relevant issue: https://github.com/AcalaNetwork/chopsticks/issues/666

**Comment by lrazovic** [comment]
Forgive my ignorance, but what do you mean by `RuntimeSpec` struct? I have searched in the SDK (https://github.com/search?q=repo%3Aparitytech%2Fpolkadot-sdk%20RuntimeSpec&type=code) and I cannot find any reference to it.

**Comment by tomaka** [comment]
Sorry, it's called `RuntimeVersion` in Substrate: https://github.com/paritytech/polkadot-sdk/blob/05381afcb2e2015fe7f379ddba7522d595a5e8cc/substrate/primitives/version/src/lib.rs#L152

**Comment by tomaka** [comment]
I tried the chain spec. The SCALE-encoded `RuntimeVersion` of the latest runtime of Polimec is:

> [60, 112, 111, 108, 105, 109, 101, 99, 45, 109, 97, 105, 110, 110, 101, 116, 60, 112, 111, 108, 105, 109, 101, 99, 45, 109, 97, 105, 110, 110, 101, 116, 1, 0, 0, 0, 136, 19, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 32, 112, 111, 108, 107, 97, 100, 111, 116, 60, 112, 97, 114, 105, 116, 121, 45, 112, 111, 108, 107, 97, 100, 111, 116, 0, 0, 0, 0, 16, 39, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 0]

All the way up to `... 0, 1, 0, 0, 0, 1`, it decodes as a `RuntimeVersion` just fine.
But then behind there's this extra data (`32, 112, ...`). I don't know why it's there, and it's because of this that smoldot returns an error.

The bytes `32, 112, 111, 108, 107, 97, 100, 111, 116, 60, 112, 97, 114, 105, 116, 121, 45, 112, 111, 108, 107, 97, 100, 111, 116` decode in ASCII to `polkadot<parity-polkadot` (without a `>` as one might expect), and then the rest of the data look like garbage.
Since this isn't intentional, it seems that there's a bug somewhere.

The way smoldot finds this runtime version is that it extracts the content of a Wasm section of the runtime Wasm binary. While it's not impossible that smoldot's parsing code has a bug, I don't see how it could produce these bytes. The bytes here are taken directly from the Wasm binary code, and if there was a Wasm section end here, we would see it, it wouldn't be ASCII.

So my bet would be that there's either a bug in Substrate's wasm builder somewhere, or a bug in the zstd library that I use to decompress the runtime.

**Comment by tomaka** [comment]
If there's a bug in Substrate's wasm builder, it is possible that Substrate manages to successfully decode the `RuntimeVersion` anyway, because they tend to accidentally use `Decode` instead of `DecodeAll`, which doesn't return an error if there's extra data at the end of the thing to decode. But I can't confirm this idea as I don't know where in Substrate is the code that decodes the runtime version.

**Comment by ermalkaleci** [comment]
I tried to debug this issue a few weeks back (not polimec runtime) and it seems it fails to decode apis length. I disabled api decoded and it seems to successfully decode the rest. This was a few weeks ago so I may be wrong. I will try again and see what I can find.

**Comment by tomaka** [comment]
> and it seems it fails to decode apis length

In the sequence `1, 0, 0, 0, 136, 19, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1`,  you have 4 bytes for the authoring version, then 4 bytes for the spec version (136, 19, 0, 0), then 4 bytes for the impl version (0, 0, 0, 0), then 1 byte for the list of APIs, then 4 bytes (1, 0, 0, 0) for the transaction version, then one byte for the state version.
It seems correct to me.

Why is the APIs list empty, you might wonder? Because when building the Wasm, the list of APIs is actually removed and added to a different Wasm section instead.

**Comment by ermalkaleci** [comment]
> Why is the APIs list empty, you might wonder? Because when building the Wasm, the list of APIs is actually removed and added to a different Wasm section instead.

interesting

**Comment by ermalkaleci** [comment]
<img width="512" alt="Screenshot 2024-03-12 at 11 41 39 AM" src="https://github.com/smol-dot/smoldot/assets/3055344/b79d4ba5-cdfb-4eb7-8967-18c8b8735ccb">
<img width="849" alt="Screenshot 2024-03-12 at 11 41 27 AM" src="https://github.com/smol-dot/smoldot/assets/3055344/94faf419-4c69-4803-b953-3b569cf27a64">

**Comment by tomaka** [comment]
> <img alt="Screenshot 2024-03-12 at 11 41 39 AM" width="512" src="https://private-user-images.githubusercontent.com/3055344/312044468-b79d4ba5-cdfb-4eb7-8967-18c8b8735ccb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDA3MjQsIm5iZiI6MTcxMDI0MDQyNCwicGF0aCI6Ii8zMDU1MzQ0LzMxMjA0NDQ2OC1iNzlkNGJhNS1jZGZiLTRlYjctODk2Ny0xOGM4Yjg3MzVjY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMTA0NzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2UwYWExMmFjOGViNDAxZmQ1YWE2MTNiYzVkMTYzMzI0MDhhMWVmYTUzNTBlZGY5YjE4ZmQ1NzUwZGEwN2QxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3rHVyHeD_bDd2yozYwmGmuLTYdM54selanM3jBWphQ4"> <img alt="Screenshot 2024-03-12 at 11 41 27 AM" width="849" src="https://private-user-images.githubusercontent.com/3055344/312044481-94faf419-4c69-4803-b953-3b569cf27a64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDA3MjQsIm5iZiI6MTcxMDI0MDQyNCwicGF0aCI6Ii8zMDU1MzQ0LzMxMjA0NDQ4MS05NGZhZjQxOS00YzY5LTQ4MDMtYjk1My0zYjU2OWNmMjdhNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMTA0NzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmNiNWZmYzM3NDcyODMxODFhNDEyZDgyMTIxNWZmY2E1NTM3MmY5NDJkMjNmZjRhZWMzYzVkNWFhZTZhYjc0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5zfHTXbhCYpmElFxIvuS2a0BpQSd-LEfTsHafcsCHn8">

This works because the `&[]` that you return is supposed to be the rest of the data. By returning `&[]`, you just discard everything behind, which is why the transaction and state versions are 0.
In order for the logic to be correct, you would have to return `Ok((bytes, CoreVersionApisRefIter { inner: &[] }))`.

**Comment by ermalkaleci** [comment]
I did add a log on `core_version_apis` I a get 2 different results
`apis: [0, 1, 0, 0, 0, 1, 32, 112, 111, 108, 107, 97, 100, 111, 116, 60, 112, 97, 114, 105, 116, 121, 45, 112, 111, 108, 107, 97, 100, 111, 116, 0, 0, 0, 0, 16, 39, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 0]`

`apis: [112, 221, 113, 141, 92, 197, 50, 98, 212, 1, 0, 0, 0, 223, 106, 203, 104, 153, 7, 96, 155, 4, 0, 0, 0, 55, 227, 151, 252, 124, 145, 245, 228, 2, 0, 0, 0, 64, 254, 58, 212, 1, 248, 149, 154, 6, 0, 0, 0, 210, 188, 152, 151, 238, 208, 143, 21, 3, 0, 0, 0, 247, 139, 39, 139, 229, 63, 69, 76, 2, 0, 0, 0, 171, 60, 5, 114, 41, 31, 235, 139, 1, 0, 0, 0, 188, 157, 137, 144, 79, 91, 146, 63, 1, 0, 0, 0, 55, 200, 187, 19, 80, 169, 162, 168, 4, 0, 0, 0, 243, 255, 20, 213, 171, 82, 112, 89, 3, 0, 0, 0, 234, 147, 227, 241, 111, 61, 105, 98, 2, 0, 0, 0, 223, 106, 203, 104, 153, 7, 96, 155, 4, 0, 0, 0, 55, 227, 151, 252, 124, 145, 245, 228, 2, 0, 0, 0, 64, 254, 58, 212, 1, 248, 149, 154, 6, 0, 0, 0, 23, 166, 188, 13, 0, 98, 174, 179, 1, 0, 0, 0, 24, 239, 88, 163, 182, 123, 167, 112, 1, 0, 0, 0, 210, 188, 152, 151, 238, 208, 143, 21, 3, 0, 0, 0, 247, 139, 39, 139, 229, 63, 69, 76, 2, 0, 0, 0, 175, 44, 2, 151, 162, 62, 109, 61, 5, 0, 0, 0, 73, 234, 175, 27, 84, 138, 12, 176, 2, 0, 0, 0, 145, 213, 223, 24, 176, 210, 207, 88, 2, 0, 0, 0, 237, 153, 197, 172, 178, 94, 237, 245, 3, 0, 0, 0, 203, 202, 37, 227, 159, 20, 35, 135, 2, 0, 0, 0, 104, 122, 212, 74, 211, 127, 3, 194, 1, 0, 0, 0, 171, 60, 5, 114, 41, 31, 235, 139, 1, 0, 0, 0, 188, 157, 137, 144, 79, 91, 146, 63, 1, 0, 0, 0, 55, 200, 187, 19, 80, 169, 162, 168, 4, 0, 0, 0, 243, 255, 20, 213, 171, 82, 112, 89, 3, 0, 0, 0]`

**Comment by tomaka** [comment]
The first time it's supposed to parse just the `0`, and the second time it's decoding the actual list from that other Wasm section that I mention above.
Everything you show indicates that things are working correctly, except for the extra data `32, 112, 111, 108, 107, 97, ...` that I explain above.

**Comment by ermalkaleci** [comment]
> The bytes `32, 112, 111, 108, 107, 97, 100, 111, 116, 60, 112, 97, 114, 105, 116, 121, 45, 112, 111, 108, 107, 97, 100, 111, 116` decode in ASCII to ` polkadot<parity-polkadot` (without a `>` as one might expect), and then the rest of the data look like garbage.

<img width="363" alt="Screenshot 2024-03-12 at 2 57 52 PM" src="https://github.com/smol-dot/smoldot/assets/3055344/35de0e75-65ad-4975-9bad-1283cca8ffc9">

only place I can find `polkadot` and `parity-polkadot` is polkadot runtime

**Comment by ermalkaleci** [comment]
`[32, 112, 111, 108, 107, 97, 100, 111, 116, 60, 112, 97, 114, 105, 116, 121, 45, 112, 111, 108, 107, 97, 100, 111, 116, 0, 0, 0, 0, 16, 39, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 0]`
will decode into 
`Ok(CoreVersionRef { spec_name: "polkadot", impl_name: "parity-polkadot", authoring_version: 0, spec_version: 10000, impl_version: 0, apis: [], transaction_version: None, state_version: None })
`

**Comment by ermalkaleci** [comment]
<img width="766" alt="Screenshot 2024-03-12 at 4 02 40 PM" src="https://github.com/smol-dot/smoldot/assets/3055344/155fdcda-9b74-42cf-a66d-e62bfe63bc4a">
<img width="1442" alt="Screenshot 2024-03-12 at 4 01 35 PM" src="https://github.com/smol-dot/smoldot/assets/3055344/a57e8185-5bf0-4099-8bd1-1f25043d516e">

there're multiple `runtime_version` section. I'm guessing polkadot is from cumulus, (not sure) but this seems to fix it

**Comment by ermalkaleci** [comment]
nah, above solution will make `find_embedded_runtime_version` return `None` which will then call `Core_version`

**Comment by tomaka** [comment]
There's only one `runtime_version` section, and it contains two versions one next to the other.

From what we see, there's no bug in smoldot. It's clearly Substrate that is wrong to generate two runtime versions.

**Comment by lrazovic** [comment]
> I tried the chain spec. The SCALE-encoded `RuntimeVersion` of the latest runtime of Polimec is:
> 
> > [60, 112, 111, 108, 105, 109, 101, 99, 45, 109, 97, 105, 110, 110, 101, 116, 60, 112, 111, 108, 105, 109, 101, 99, 45, 109, 97, 105, 110, 110, 101, 116, 1, 0, 0, 0, 136, 19, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 32, 112, 111, 108, 107, 97, 100, 111, 116, 60, 112, 97, 114, 105, 116, 121, 45, 112, 111, 108, 107, 97, 100, 111, 116, 0, 0, 0, 0, 16, 39, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 0]
> 
> All the way up to `... 0, 1, 0, 0, 0, 1`, it decodes as a `RuntimeVersion` just fine. But then behind there's this extra data (`32, 112, ...`). I don't know why it's there, and it's because of this that smoldot returns an error.
> 
> The bytes `32, 112, 111, 108, 107, 97, 100, 111, 116, 60, 112, 97, 114, 105, 116, 121, 45, 112, 111, 108, 107, 97, 100, 111, 116` decode in ASCII to ` polkadot<parity-polkadot` (without a `>` as one might expect), and then the rest of the data look like garbage. The `32` might be not an ASCII space but instead some kind of length prefix, however `polkadot<parity-polkadot` is only 24 bytes long, and the whole data is 42 bytes, so I'm leaning more towards an ASCII space. Since this isn't intentional, it seems that there's a bug somewhere.
> 
> The way smoldot finds this runtime version is that it extracts the content of a Wasm section of the runtime Wasm binary. While it's not impossible that smoldot's parsing code has a bug, I don't see how it could produce these bytes. The bytes here are taken directly as a slice of the Wasm binary code, and if there was a Wasm section end here, we would see it, it wouldn't be ASCII.
> 
> So my bet would be that there's either a bug in Substrate's wasm builder somewhere, or (IMO less likely) a bug in the zstd library that I use to decompress the runtime.

I think I found why there is the `polkadot<parity-polkadot` in the SCALE-encoded `RuntimeVersion` of the latest runtime of Polimec. 

One of the crates in our runtime depends on Polkadot's Runtime [^1] , which might be why we see information from this runtime included in our RuntimeVersion. This likely also ties into the issue @ntn-x2 raised [^2], since also that faulty runtime depends on Rococo's Runtime[^3], leading to a similar kind of "interference" in the `RuntimeVersion`.

[^1]: https://github.com/Polimec/polimec-node/blob/28c7bf1313f79ab3248933be4f4f5cc41eb94f1c/pallets/funding/Cargo.toml#L43
[^2]: https://github.com/AcalaNetwork/chopsticks/issues/666
[^3]: https://github.com/KILTprotocol/kilt-node/blob/13d9921ea518150c89b9cfa7af500ae9fe19a78e/dip-template/runtimes/dip-consumer/Cargo.toml#L64

**Comment by tomaka** [comment]
I'm going to close this, as it's not a smoldot bug but a Substrate bug.
