### ISSUE TITLE
New Hostfunction

### ISSUE THREAD

**Issue by NachoPal** [smol-dot/smoldot#1721]
When trying to to run Chopsticks using the latest `asset-hub-rococo-runtime` as genesis, I ran into this issue: https://github.com/AcalaNetwork/chopsticks/issues/691

Apparently the reason is that a new Hostfunction has been recently added: https://github.com/paritytech/polkadot-sdk/pull/3002

**Comment by ermalkaleci** [comment]
@tomaka this is now on Westend Asset-Hub

**Comment by ermalkaleci** [comment]
#1742

**Comment by tomaka** [comment]
Closing after #1742
