### ISSUE TITLE
Use new `wasmi::LinkerBuilder` to improve startup time (?)

### ISSUE THREAD

**Issue by Robbepop** [smol-dot/smoldot#1779]
Wasmi `v0.32.0-beta.9` introduced the new `LinkerBuilder` API which can be used to quickly spin up new `Linker` instances whenever a new `Engine` is created. The `LinkerBuilder` can be used to pre-define a set of host functions and create `Linker` instances with this same set of host functions a lot more quickly afterwards.

However, setting up a `LinkerBuilder` initially is as costly as setting up a `Linker` without `LinkerBuilder`.

I implemented this for the `contracts-pallet` which has to create a new `Engine` per smart contract call (unfortunately).
Spinning up a new `Linker` using `LinkerBuilder` improves performance of `Linker` setup with 52 host functions by a factor of 6.

I was wondering if this optimization could also be applied to `smoldot` to improve its startup time further.

From what I see this is where `smoldot` uses Wasmi's `Linker`:
https://github.com/smol-dot/smoldot/blob/60d66124b10ccb4927161630fafc7c3d0a6641ab/lib/src/executor/vm/interpreter.rs#L120

It creates host functions on demand, so it might either need some refactoring to make use of `LinkerBuilder` or won't profit from it a lot.

**Comment by tomaka** [comment]
We could indeed put `LinkerBuilder` in `BaseComponents`.
The `BaseComponents` struct is basically a builder.

**Comment by Robbepop** [comment]
You should probably wait for https://github.com/wasmi-labs/wasmi/pull/996 since I speed-up the `Linker` creation process by another 20x, totaling in 120x faster `Linker` setup compared to before.
