### ISSUE TITLE
Make wasm platform public

### ISSUE THREAD

**Issue by Kofituo** [smol-dot/smoldot#1984]
I'm working on a code that's wasm only. I'd like to use smoldot over subxt since smoldot works with the bootnodes. My issue now is the wasm platform to use
I see a working example here 
https://github.com/smol-dot/smoldot/blob/837d9c3f418ec39b2acab3a404423b58117329a8/wasm-node/rust/src/lib.rs#L42

But I'm not sure why it isn't publicly available. Are there any plans to make it available or are there any alternatives?

**Comment by tomaka** [comment]
I'm not really sure what you're trying to do. The `wasm-node` crate is only ever meant to be compiled a specific way and then integrated within the JS package. The `platform` module closely interacts with the JavaScript code in `wasm-node/javascript` and can't be used with for example `wasm-bindgen`.

**Comment by Kofituo** [comment]
I've been able to find an alternative with subxtlightclient. Thanks
