### ISSUE TITLE
`RangeError [Error]` when using `startFromWorker` API

### ISSUE THREAD

**Issue by josepot** [smol-dot/smoldot#2045]
Sometimes, when using the `startFromWorker` API I get the following error:

![image](https://github.com/user-attachments/assets/022a2a02-1dcc-4313-8555-5aff9f6126d6)

In most cases this issue doesn't happen in a deterministic manner, but somehow I managed to create [a reproduction ](https://github.com/josepot/smoldot-worker-race-condition)where the issue does happen deterministically.

**Comment by tomaka** [comment]
Your repro doesn't run on my system as I only have NodeJS v18, and I don't want to spend hours figuring out the clusterfuck that is installing a custom NodeJS version.

**Comment by josepot** [comment]
> Your repro doesn't run on my system as I only have NodeJS v18, and I don't want to spend hours figuring out the clusterfuck that is installing a custom NodeJS version.

Simplest and most reliable way to manage different node versions is using [nvm](https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating), eg:

```bash
nvm i 20
```

Also, FYI: node 18 is[ not even "active" anymore](https://nodejs.org/en/about/previous-releases#release-schedule).
