### ISSUE TITLE
Unable to connect to `people-polkadot` chain

### ISSUE THREAD

**Issue by carlosala** [smol-dot/smoldot#2061]
When trying to connect to People Polkadot parachain I'm getting `SubstreamReset` errors with all bootnodes. `polkadot-sdk` node with the same chainspec seems to have no issues to get more peers and continue. After a few minutes (~5min), it is indeed able to get peers and get the runtime.
This happens with any IP I tried, so I don't think is a connectivity / rate limiting issue.
I'm not very familiar with the networking internals of smoldot, I might have oversight something.

Chainspec:
```json
{
  "name": "Polkadot People",
  "id": "people-polkadot",
  "chainType": "Live",
  "bootNodes": [
    "/dns/polkadot-people-connect-0.polkadot.io/tcp/30334/p2p/12D3KooWP7BoJ7nAF9QnsreN8Eft1yHNUhvhxFiQyKFEUePi9mu3",
    "/dns/polkadot-people-connect-1.polkadot.io/tcp/30334/p2p/12D3KooWSSfWY3fTGJvGkuNUNBSNVCdLLNJnwkZSNQt7GCRYXu4o",
    "/dns/polkadot-people-connect-0.polkadot.io/tcp/443/wss/p2p/12D3KooWP7BoJ7nAF9QnsreN8Eft1yHNUhvhxFiQyKFEUePi9mu3",
    "/dns/polkadot-people-connect-1.polkadot.io/tcp/443/wss/p2p/12D3KooWSSfWY3fTGJvGkuNUNBSNVCdLLNJnwkZSNQt7GCRYXu4o",
    "/dns/people-polkadot-boot-ng.dwellir.com/tcp/443/wss/p2p/12D3KooWKMYu1L28TkDf1ooMW8D8PHcztLnjV3bausH9eiVTRUYN",
    "/dns/people-polkadot-boot-ng.dwellir.com/tcp/30346/p2p/12D3KooWKMYu1L28TkDf1ooMW8D8PHcztLnjV3bausH9eiVTRUYN"
  ],
  "telemetryEndpoints": null,
  "protocolId": null,
  "properties": {
    "ss58Format": 0,
    "tokenDecimals": 10,
    "tokenSymbol": "DOT"
  },
  "relay_chain": "polkadot",
  "para_id": 1004,
  "codeSubstitutes": {},
  "genesis": {
    "stateRootHash": "0x7a62a14ebf9b2e86292593414d58818324acc5701ea369734c0074f7c962bc0f"
  }
}
```
[Some smoldot logs](https://github.com/user-attachments/files/18027487/logs.log)

Thanks!

**Comment by tomaka** [comment]
Unfortunately there's not much I can do with just the smoldot logs. All I know is that the Polkadot People full nodes reject smoldot with no reason given.

Since polkadot-sdk successfully connect, it might be that People-People is somehow configured to reject light clients but accept full nodes.

To debug this, we need the logs of the Polkadot People full node, which would indicate why they do that.

**Comment by carlosala** [comment]
While debugging this with a local node, I couldn't reproduce it. After retrying with the same set of bootnodes as above, the issue was resolved. It was most likely an issue with the bootnodes, closing then.
Thanks!
