### ISSUE TITLE
Circumvent non-wss nodes in https browser environments

### ISSUE THREAD

**Issue by rossbulat** [smol-dot/smoldot#2066]
In https browser environments, browsers disallow connecting to ws endpoints, as opposed to wss enpoints. This slows down the Smoldot connection process and yields console errors within the web browser.

Is it feasible to have a config option that forces Smoldot to only connect to WSS boot nodes, or is there an alternative to avoid this behaviour?

Thank you!

Errors for reference:
<img width="357" alt="Screenshot 2024-12-19 at 20 29 50" src="https://github.com/user-attachments/assets/96b947b6-60bb-4dd3-bcf1-a480b1f38330" />

**Comment by josepot** [comment]
In order to avoid this, you can set the `forbidWs` option to `true` when starting smoldot.
