### ISSUE TITLE
Panic when connecting to chain with no finalized blocks

### ISSUE THREAD

**Issue by skunert** [smol-dot/smoldot#253]
I am trying to write tests that spin up various nodes in a testnet. One of these is a parachain collator with an embedded smoldot light-client instance. I saw some failures there due to this assumption in the code:
https://github.com/smol-dot/smoldot/blob/9f44aaf50a9588eb30b70c4795d08408f6d7fcc9/lib/src/chain/chain_information/build.rs#L184

If I understand correctly, the failure happens when smoldot joins the relay chain network, and no blocks have been finalized yet. My current hacky workaround is to wait a few seconds before initializing smoldot internally, but it would be nicer if smoldot could tolerate this scenario. 

**Error Message**
```
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', ~/.cargo/git/checkouts/smoldot-2dcbf637e11a77d4/54d8889/lib/src/chain/chain_information/build.rs:184:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { kind: Disconnected }', ~/.cargo/git/checkouts/smoldot-2dcbf637e11a77d4/54d8889/light-base/src/sync_service.rs:211:14
```

**Comment by tomaka** [comment]
The warp sync code indeed doesn't really expect the chain to still be at block 0.

While this issue itself is relatively easy to fix (2/3 lines of code), I'm going to read/review the warp sync code and check if everything is correct if we're still at the genesis.
