### ISSUE TITLE
Backport changes to multiaddr WebRTC

### ISSUE THREAD

**Issue by tomaka** [smol-dot/smoldot#275]
https://github.com/multiformats/multiaddr/pull/150

**Comment by tomaka** [comment]
It's actually not clear to me what is happening, if anything.
Did `/webrtc` get renamed to `/webrtc-direct`? Or not?

cc @melekes ^ :pray:

**Comment by melekes** [comment]
https://github.com/multiformats/multiaddr/pull/150#issuecomment-1468795759
