### ISSUE TITLE
Parachain compatibility broken: UnusedProofEntry on token transfer

### ISSUE THREAD

**Issue by bLd75** [smol-dot/smoldot#416]
During latest tests, we realized smoldot can't make transfer on parachain anymore with the following message:
`[tx-service-shibuya] Failed to validate transaction 0xb4f0…bff4: Error in call proof: UnusedProofEntry`

The connection is well established with relay (tokyo) and para (shibuya). 
Transfers work for any relay chain.
Transfer don't work with parachain.

How to reproduce
- clone the smoldot fork here https://github.com/bLd75/smoldot
- start the wasm-node
- send a token transfer on Shibuya (https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944%2Fshibuya)

Shibuya tokens can be obtained just requesting the faucet here: https://portal.astar.network/shibuya-testnet/assets

**Comment by tomaka** [comment]
I will check it out :+1: 

For what it's worth, a similar issue was found two months ago (https://github.com/smol-dot/smoldot/issues/154) and fixed by https://github.com/paritytech/substrate/pull/13284

If you don't have https://github.com/paritytech/substrate/pull/13284 in, then unfortunately that'd be the cause.

**Comment by bLd75** [comment]
Thanks @tomaka so that may be it, Astar is not yet uplifted to polkadot-v0.9.39 including this fix.
We'll uplift soon and check the issue again as soon as upgrade is made.

**Comment by tomaka** [comment]
For what it's worth, this was a bug in Substrate that happens when you transition to `state_version = 1`. This is most likely why it used to work in the past but now no longer.

**Comment by bLd75** [comment]
@tomaka I'm closing the issue, para compatibility is back after upgrade to polkadot-v0.9.39, thanks
