### ISSUE TITLE
Error in call proof: UnusedProofEntry 

### ISSUE THREAD

**Issue by Douglasacost** [smol-dot/smoldot#567]
Hello guys, I'm trying to implement this light-client on a webpage (Using the WASM strategy)

Here the RPC method sent
```{"id":1,"jsonrpc":"2.0","method":"author_submitExtrinsic","params":["0x45028400c6f5bc3043731278e954cd2bf0456a0b7e5b28121af089fdc8353c8fe751255f016009373033f8488f20e970258013886c56c6ed73619820b1ed913ecf32b9db479803a0c524681cb9512dd11b3782eadf73abcdd728017ca0280b779c22bc2a8b2400510900020000dc4b5cae108e10211c6641d7f90dca8ad6f5727e4a307507f3341adffe2f37020700cc829c19"]}```

I got this response
```JSON-RPC response: {"jsonrpc":"2.0","method":"author_extrinsicUpdate","params":{"subscription":"0","result":"Dropped"}}```

This trigger this warning `[tx-service-para_eden] Failed to validate transaction 0xed38…bf7e: Error in call proof: UnusedProofEntry thus the transaction wasn't relayed`

I have sent the transaction trough Polkadot.js app and works fine using the same method `author_submitExtrinsic`

Probably I'm missing something, could you help me to figure out what is wrong?

Here the implementation file: https://gist.github.com/Douglasacost/24597aaba31473c6903ba27828dfd2f3

**Comment by tomaka** [comment]
Hi!

This is probably the same bug as https://github.com/smol-dot/smoldot/issues/154 and https://github.com/smol-dot/smoldot/issues/416.

It's a Substrate bug that was fixed by https://github.com/paritytech/substrate/pull/13284

Given the fact that it keeps being reported, I might add a work-around in smoldot for the time being.

**Comment by tomaka** [comment]
On a side note, looking at your code, there really is no need to batch JSON-RPC requests. If batching requests solves some kind of problem that you have, please report it as an issue.

**Comment by Douglasacost** [comment]
> On a side note, looking at your code, there really is no need to batch JSON-RPC requests. If batching requests solves some kind of problem that you have, please report it as an issue.

Not there is no issue, thanks for the observation

**Comment by Douglasacost** [comment]
> Hi!
> 
> This is probably the same bug as #154 and #416.
> 
> It's a Substrate bug that was fixed by [paritytech/substrate#13284](https://github.com/paritytech/substrate/pull/13284)
> 
> Given the fact that it keeps being reported, I might add a work-around in smoldot for the time being. The only issue with such a work-around is that it would prevent similar Substrate bugs from being discovered.

is there something I can do from my side?

**Comment by tomaka** [comment]
> is there something I can do from my side?

The chain you're connecting to (`para_eden`) should update its version of Substrate

**Comment by Douglasacost** [comment]
Start working with the recent substrate upgrade. Thanks @tomaka
