### ISSUE TITLE
smoldot-light: GrandPa warp sync idle at block

### ISSUE THREAD

**Issue by lexnv** [smol-dot/smoldot#592]
Hi, I'm trying to integrate smoldot-light in https://github.com/paritytech/subxt/pull/965, locally on my mac M1 it works perfectly, on AMD x86 the light client seems stuck on:

```bash
2023-05-22T10:31:36.572347Z  WARN sync-service-dev: GrandPa warp sync idle at block #0 (0x0xaee0…6e8a)
2023-05-22T10:31:46.573234Z  WARN sync-service-dev: GrandPa warp sync idle at block #0 (0x0xaee0…6e8a
```

Im starting my polkadot nodes the same, and Im using the same chain spec

```
./polkadot --dev --tmp --alice --validator

spec:
  "bootNodes": [
      "/ip4/127.0.0.1/tcp/30333/p2p/12D3KooWKGrBgNaxndgc61G4P9UKnJSgCQjqmb6jRfEg6kxirD86"
  ],
```

Im using polkadot version on x86 cbd5330173, compared to 6dc9e84dde2 for mac.

Do you know what might cause this warning?

**Comment by tomaka** [comment]
Please run smoldot with `debug` logging in order to get more information about what happens.

My immediate suspicion is that the PeerId of the chain spec is wrong because you're running with `--tmp`, or something like that.

**Comment by lexnv** [comment]
Hi,

I've managed to get this working by doing the following:
- Started polka-dot with:

```bash
./polkadot-cbd5330173 --dev --node-key 0000000000000000000000000000000000000000000000000000000000000001  --alice --validator
```

This produces the same genesis hash and the same node identity

- Fetched the spec

```bash
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "sync_state_genSyncSpec", "params":[true]}' http://localhost:9944/ | jq .result > res.spec
```

- Modified the spec
  - Removed the `lightSyncState` entry
  - Added the bootnode address
  

If I were to leave the `lightSyncState` the smoldot will panic on the following: 

https://github.com/smol-dot/smoldot/blob/main/lib/src/chain_spec.rs#L445-L446

Would it be possible that the "freshly" spawned local node does not have 2 epochs yet?

Is there a way to avoid this, but still benefit from the `lightSyncState`? I think that the warp syncing is a bit slow because I don't provide this (around 2~5 minutes)

**Comment by tomaka** [comment]
> I think that the warp syncing is a bit slow because I don't provide this (around 2~5 minutes)

The warp sync time is proportional to the length of the chain. Every epoch (4096 blocks? I believe), there's one signature per validator to download and validate. When the chain is several million blocks, this adds up and causes slowness. But for a local chain that has just started, it is really not supposed to take more than a few dozen milliseconds.

**Comment by tomaka** [comment]
I'm a bit confused about whether you (still) have a problem. If you need help with the warp syncing being stuck, I would need the `debug` logs of smoldot.

**Comment by lexnv** [comment]
The CPU consumption is at 100% for 1 CPU, while the others are idle all the time, verified with `htop` seems that the light client is consuming that CPU

**Comment by tomaka** [comment]
Another question is: did you truncate the logs between `15:36:53.446268Z` and `15:38:39.646368Z`?
If yes I do need the actual logs to understand what happens.

**Comment by tomaka** [comment]
https://github.com/smol-dot/smoldot/pull/645 and https://github.com/smol-dot/smoldot/pull/644 add a lot of logs which could be useful to understand the problem

**Comment by lexnv** [comment]
Hey, I did enable tracing for my example run, however, the transaction gets dropped after a while resulting in some 271 MB of logs. I expect this to be related to the large number of logs.

I ended up running `RUST_LOG="smoldot=debug,network=debug,runtime-dev=debug,connections=debug,json-rpc-dev=debug" cargo run --example tx_basic_light_client` for the provided logs.

Will retry the experiment fetching those two PRs, thanks! 🙏

**Comment by lexnv** [comment]
I've updated the full logs at my [drive](https://drive.google.com/drive/folders/1IPUEDS50YDamlUza5VkTGvVJnJSdWrEd).

- smoldot-31-panic.logs: 
```bash
thread 'async-std/runtime' panicked at 'explicit panic', /home/lexnv/workspace/smoldot/lib/src/sync/all.rs:1791:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

- smoldot-31-2.logs

The tx was submitted successfully in around 5 minutes

**Comment by lexnv** [comment]
I've uploaded another file to the drive `smoldot-1-06.logs`, after fetching the latest origin the logs indicate that `GrandPa warp sync in progress` for about 10 minutes

**Comment by tomaka** [comment]
It is now possible to no longer use `wasmtime` and instead always `wasmi` (#695), so you could try doing that.

**Comment by tomaka** [comment]
I don't really have any hypothesis except that you're reaching the computation limits of your machine.
While smoldot alone should be able to run on any machine just fine, if you run smoldot plus other nodes at the same time it's not completely surprising for things to be slow.
