### ISSUE TITLE
Panicked while executing task `json-rpc-westend2-requests-13`

### ISSUE THREAD

**Issue by wirednkod** [smol-dot/smoldot#594]
When trying to connect to smoldot on Westend (app: Polkadot staking dashboard) the following issue appears:

```
[runtime-westend2] Finalized block runtime ready. Spec version: 9420. Size of `:code`: 1.2 MiB.
index-204b3592.js:805 Smoldot has panicked while executing task `json-rpc-westend2-requests-13`. This is a bug in smoldot. Please open an issue at https://github.com/smol-dot/smoldot/issues with the following message:
panicked at 'explicit panic', light-base/src/runtime_service.rs:942:13
onWasmPanic @ index-204b3592.js:805
onPanic @ index-204b3592.js:805
panic @ index-204b3592.js:804
.....
onMessage @ index-204b3592.js:804
d0.onmessage @ index-204b3592.js:806
index-204b3592.js:822 Uncaught CrashError: panicked at 'explicit panic', light-base/src/runtime_service.rs:942:13
    at transformErrors (index-204b3592.js:822:1044157)
    at sendJsonRpc (index-204b3592.js:822:1044654)
    at InnerChecker.__internal__requestToSmoldot (index-204b3592.js:801:41888)
    at r0 (index-204b3592.js:801:40295)
```

On Kusama and Polkadot everything seems to work normally

![image](https://github.com/smol-dot/smoldot/assets/5408605/24b50fb3-472e-46a2-8d86-11f1dc511566)

To reproduce:

- Navigate to https://staking.polkadot.network/
- Select on the left-hand and bottom side (Network), Westend + light client
- See browser console

**Comment by rossbulat** [comment]
I am not sure if this is related, but it also cannot progress past the api creation line when I switch to light client (Chrome):
```
const newApi = await ApiPromise.create({ provider: newProvider });
```

<img width="1536" alt="Screenshot 2023-05-24 at 12 11 16" src="https://github.com/smol-dot/smoldot/assets/13929023/f9803419-d2e3-4a37-abec-a0f19cb2c710">

**Comment by wirednkod** [comment]
Just realized that live version of Polkadot Staking Dashboard contains smoldot v.1.0.3 (through SC). This bug is corrected on latest Substrate Connect that contains Smoldot 1.0.4 - thus PSD needs to update accordingly.
