### ISSUE TITLE
chainhead_unstable_body: Returns two values

### ISSUE THREAD

**Issue by lexnv** [smol-dot/smoldot#614]
Calling the `chainhead_unstable_body` RPC method produces a response of the following form:

`{"jsonrpc":"2.0","method":"chainHead_unstable_bodyEvent","params":{"subscription":"3","result":{"event":"done","value":["0x280403000b21dace528801","0x9aff0100043600.."]}}}`

Substrate implementation produces a single value as a response, similar to:
`Done(ChainHeadResult { result: "0x0.." })` 

Calling the `chainHead_unstable_storage` produces just one value, similar to substrate.

### Repro case
Added the following to the chainHead part of the light-client example from: https://github.com/paritytech/subxt/pull/965

```
// Fetch the body of the block.
let mut sub = api
    .rpc()
    .chainhead_unstable_body(sub_id.clone(), hash)
    .await?;

if let Some(event) = sub.next().await {
    let event = event?;
    println!("  chainhead_unstable_body event: {event:?}");
}
```

**Comment by tomaka** [comment]
The spec mentions an array: https://paritytech.github.io/json-rpc-interface-spec/api/chainHead_unstable_body.html#done

I suppose that the Substrate implementation returns all the extrinsics concatenated together?

**Comment by lexnv** [comment]
Yep, seems that I returned all extrinsics concatenated here:

https://github.com/paritytech/substrate/blob/0cf64f8bd72d719818be2f109c0919c7c9325cd1/client/rpc-spec-v2/src/chain_head/chain_head.rs#L229-L232

Thanks for the help!

**Comment by tomaka** [comment]
Since this is a Substrate problem, this should be an issue in the Substrate repository, so I would close this.
