### ISSUE TITLE
Relax Wasmtime version constraints

### ISSUE THREAD

**Issue by skunert** [smol-dot/smoldot#690]
In order to push https://github.com/paritytech/cumulus/pull/2270 over the finish line, I am asking if we can relax the constraints on the wasmtime version in smoldot. Including two different versions of wasmtime in the dependency tree leads to errors in the linking phase of the binary.

If it is possible to relax the wasmtime version to something like ">=7", we could let cargo pick an appropriate version during build.

**Comment by tomaka** [comment]
Ideally it would be `>= 8`, because their policy is to maintain one version before the latest one:

> Patch releases of Wasmtime will only be issued for security and critical correctness issues for on-by-default behavior in the previous releases. If Wasmtime is currently at version 5.0.0 then 5.0.1 and 4.0.1 will be issued as patch releases if a bug is found. Patch releases are guaranteed to maintain API and behavior backwards-compatibility and are intended to be trivial for users to upgrade to.

(https://docs.wasmtime.dev/stability-release.html#release-process)

Is 8 possible?

**Comment by tomaka** [comment]
One issue if semantics are relaxed is that dependabot will probably no longer detect updates to wasmtime.

**Comment by skunert** [comment]
So basically there are some settings that were deprecated in v9, see the comment here 
https://github.com/skunert/substrate/blob/55bb6298e74d86be12732fd0f120185ee8fbfe97/client/executor/wasmtime/src/runtime.rs#L292-L295
I am not too familiar with this specific setting and its impact, so I think we will upgrade at some point but have not yet. 

In my opinion, it is a good idea anyway to have some wiggle room here since the updates of wasmtime will probably not be very synchronous in the future too. We could safely update smoldot in cumulus without waiting for substrate and smoldot wasmtime version to be exactly the same.

**Comment by tomaka** [comment]
What about instead giving the option to remove wasmtime from smoldot with a feature flag, so that it always uses wasmi?
There's normally no CPU-intensive runtime calls when using a light client.

**Comment by skunert** [comment]
> I'm unfortunately a bit pessimistic when it comes to Substrate and doing things on time in general. The last thing I want is not being able to update `wasmtime` because Substrate is blocked on some niche issue, such as the one you linked, that people put in a dusty corner for months.

I understand. The suggestion was more to allow compatible versions here as long as there are no breaking changes. Even with `>=8`, everyone is free to use the newest version. If substrate is on an old version, that is on us. In case smoldot needs some new features that are only available on a specific version, you could still bump the requirement.

> What about instead giving the option to remove wasmtime from smoldot with a feature flag, so that it always uses wasmi?
There's normally no CPU-intensive runtime calls when using a light client.

This approach would also work for me. So if you prefer this, also fine :+1:. Is there already a way to force wasmi everywhere, just for some testing?

**Comment by tomaka** [comment]
I will do the optional wasmtime thing no matter what, because in theory Substrate is not necessarily the only project that would want to use smoldot and an old version of wasmtime at the same time.

> Is there already a way to force wasmi everywhere, just for some testing?

You could by modifying the code of `smoldot-light-base` (pass `ExecHint::ForceWasmi` everywhere there's an `ExecHint`), but not through the public API it exposes.

**Comment by skunert** [comment]
Thanks for the quick fix, worked as expected :+1:
