### ISSUE TITLE
[master branch] At least O(n²) complexity in `ChainSpec.to_chain_information`

### ISSUE THREAD

**Issue by DragonDev1906** [smol-dot/smoldot#745]
Just as an info in advance (since this commit isn't in a release version, yet), I just noticed it because I needed a newer version for syncing from genesis.

`ChainSpec.to_chain_information` currently has a complexity of at least O(n²) if `GenesisStorage` contains items because it is building a new BTreeSet over all storage items for every storage item. It is a bit more than that since the BTreeSet inserts are not O(n), but I don't know the exact complexity.

Calling this function for the Kusama specification in the polkadot repo [^1] takes 4 Minutes on my machine. That's not a big deal because it only needs to run once, but I wasn't sure if you're aware of this. There are two TODOs mentioning a borrow checker issue, which is probably why the function is written this way.

If I understood it correctly, we're cloning a BTreeSet just to take out a single entry as an iterator, which is then collected back into a `Vec<u8>` afterwards. This shouldn't require copying the entire BTreeSet (I think).

Introduced in 760e2c98129615e063a132ce9c7371cf168b0c78

[^1]: https://github.com/paritytech/polkadot/blob/master/node/service/chain-specs/kusama.json

**Comment by tomaka** [comment]
:+1: The whole `chain_spec` module needs a lot of love to fix the many TODOs.
