### ISSUE TITLE
Kusama 1492436: verify_justification fails with `NotEnoughSignatures`

### ISSUE THREAD

**Issue by DragonDev1906** [smol-dot/smoldot#749]
I think I've found another bug when syncing older Kusama blocks.

When trying to verify the justification of Kusama block 1492436 (3/17/2020) [^1] I get the following error: `VerificationFailed(NotEnoughSignatures)`, which is unexpected because the block is included in the canonical chain according to PolkadotJs [^1].

The authority set had size 180 at the previous justification (1492283) and so smoldot expects at least 121 Signatures. But for some reason (again, could also be that I'm getting bad data from PolkadotJs, which I find unlikely) the decoded `GrandpaJustificationRef` only contains 37 precommits. My current best guess is that this is related to the amount of Disabled grandpa consensus messages (see [^2] for decoding the consensus messages) or because of some decoding error in the justification.

I don't think I've used it wrong, since it has worked for so many other justifications: Call and insert `verify_header` for at least all blocks until the justification block (inclusive), then call `verify_justification`. See the attached code (too big for Github
[kusama-justification-error.rs.txt](https://github.com/smol-dot/smoldot/files/11756711/kusama-justification-error.rs.txt)
 due to including the headers).

> 3: Implies on disabled: An index to the individual authority in the current authority list ([Definition 33](https://spec.polkadot.network/chap-sync#defn-authority-list)) that should be immediately disabled until the next authority set changes. When an authority gets disabled, the node should stop performing any authority functionality from that authority, including authoring blocks and casting GRANDPA votes for finalization. Similarly, other nodes should ignore all messages from the indicated authority which pertain to their authority role. [^2]

For context: I've created this chain_information by syncing from genesis on Kusama.
Commit I tested this on: c7f6dd38052aae9dbcf179b7531fc4876d62e2f2 

[^1]: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/explorer/query/1492436
[^2]: https://spec.polkadot.network/sect-finality#defn-consensus-message-grandpa

# Output
```
[substrate-adapter/src/bin/kusama-justification-error.rs:186] tree.best_block_header().number = 1492283
[substrate-adapter/src/bin/kusama-justification-error.rs:210] decoded.precommits.iter().count() = 37
[substrate-adapter/src/bin/kusama-justification-error.rs:211] decoded.round = 2
[substrate-adapter/src/bin/kusama-justification-error.rs:212] decoded.target_hash.encode_hex::<String>() = "ddc4323c5e8966844dfaa87e0c2f74ef6b43115f17bf8e4ff38845a62d02b9a9"
[substrate-adapter/src/bin/kusama-justification-error.rs:213] decoded.target_number = 1492436
[substrate-adapter/src/bin/kusama-justification-error.rs:214] decoded.votes_ancestries.len() = 0
[substrate-adapter/src/bin/kusama-justification-error.rs:215] tree.best_block_hash().encode_hex::<String>() = "70e916fd3c78bc544bda5522c9f413410b35797319abd6f2f08277c838c1cd0b"
[substrate-adapter/src/bin/kusama-justification-error.rs:216] tree.best_block_header().number = 1492437
thread 'main' panicked at 'to succeed: VerificationFailed(NotEnoughSignatures)', substrate-adapter/src/bin/kusama-justification-error.rs:220:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by DragonDev1906** [comment]
Interesting, I did not know about that. This is one of those hard-coded fork blocks.

So let's say (just in theory) I need/want to check validity through this hard fork or this happens again tomorrow. Is there a way to handle this situation (manually) with the methods available in smoldot or are there only the following options?
- Handle things that happen during this fork manually (process these blocks without grandpa finalization and have a hard-coded hash to manually finalize them outside of smoldot by comparing against this hash), then start new using a checkpoint after the hard fork with a new `NonFinalizedTree`
- Fork and modify smoldot code (at least while the fork is processed)
- Use substrate (not sure if I can do that given the restrictions I have, I choose smoldot because it matched way more closely to what I need)
- Use `unsafe` code to "trick" smoldot into finalizing something without a justification proof

I don't need to start at the genesis block, but I'd like to know what I'd have to do if that happens in the future (probably the first option is the easiest).

**Comment by DragonDev1906** [comment]
Do you know of a good way to get a chain specification with checkpoint (or a persisted `ValidChainInformation`) at a specific block (preferably without needing a fully synced local full node)?

There is the `syncState.getSyncSpec(raw)` rpc endpoint, but that doesn't allow selecting a block to do this at. So the only thing I can currently think about is building the `ChainInformation` object manually (in json if needed) using multiple rpc requests to get the data needed (e.g. grandpa authorities, babe authorities, ...).

I've seen that you're using that endpoint to get the latest chain spec with a checkpoint in [generate_chain_spec.sh](https://github.com/smol-dot/smoldot/blob/main/demo-chain-specs/generate_chain_spec.sh), but that unfortunately only allows me to get the latest state. I'd like to try syncing from directly after the hard fork instead of skipping a few million blocks (free data to test if the code works).

**Comment by tomaka** [comment]
> Use unsafe code to "trick" smoldot into finalizing something without a justification proof

That's how you would do it. This is however not related to the `unsafe` keyword, as `unsafe` is specifically for memory unsafety.

It is already possible to set the finalized block "no questions asked" using [`set_finalized_block`](https://docs.rs/smoldot/latest/smoldot/chain/blocks_tree/struct.NonFinalizedTree.html#method.set_finalized_block).
My suggestion would be: when a block has been successfully verified, check if its hash is equal to a specific hardcoded hash, and if so call `set_finalized_block`.

If smoldot was to support this hard fork, the support would be at the highest-level. The code of `NonFinalizedTree` shouldn't be aware of any magic like that.

> Do you know of a good way to get a chain specification with checkpoint (or a persisted ValidChainInformation) at a specific block (preferably without needing a fully synced local full node)?

I don't think there's an easy way to do this.

As far as I remember, the `syncState_getSyncSpec` JSON-RPC method can realistically only work at the head of the chain without heavy modifications.

**Comment by DragonDev1906** [comment]
This approach did work. In case anyone else has this issue at some point:
I'm now ignoring all justifications between 1492283 and 1500988 (inclusive), using a hard coded hash at 1500988 to finalize this range and can then continue normally.
