### ISSUE TITLE
`NonFinalizedTree<T>` O(n²) complexity when updating the best block to None

### ISSUE THREAD

**Issue by DragonDev1906** [smol-dot/smoldot#757]
`NonFinalizedTree::set_finalized_block` has to update the current best block if it is not a decendant of the current block. Lets say we have the following situation (this happened when I tried to sync from genesis on Polkadot using my own sync mechanism):
- We have called `NonFinalizedTree::verify_header` a lot of times (e.g. 300_000 times on Polkadot because I cannot finalize them earlier, at least not when using the json rpc api to get justifications)
- We want to call `NonFinalizedTree::verify_justification` on the last block added to the tree
- All blocks are in one row, there are no forks
- All blocks are ancestors of the block to be finalized

Visualization of this situation:
```
                 Justification proof
                         ↓
#0 ← #1 ← #2 ← ... ← #300_000
                         ↑
                 Current best block
```

When applying the finality (`set_finalized_block`) the current best block is set to `None`, because the `NonFinalizedTree` is empty. Unfortunately this has the complexity O(n²), which takes a a long time if n == 300_000 blocks:

https://github.com/smol-dot/smoldot/blob/main/lib/src/chain/blocks_tree/finality.rs#L434-L439

It would be nice if `ForkTree::is_ancestor` or the loop linked above would use the block number to check if it has to iterate over the entire ancestor history for every block. All blocks with a lower number than the block to be finalized cannot possibly be the new best block. The current implementation basically does the following:
```rust
for block in tree {
    let mut block = block;
    while block.parent != None {
        block = block.parent.unwrap()
    }
}
```

This would reduce the complexity to O(n) while not really adding any (significant) overhead, just a comparison.

My current approach to avoiding this (it is only problematic when finalizing a lot of blocks at once, but is a performance penalty if we only add headers needed for verifying the justification) is to add an extra header (even though it is not needed for verifying the justification or to get correct behavior):

```
                 Justification proof
                         ↓
#0 ← #1 ← #2 ← ... ← #300_000 ← #300_001
                                    ↑
                            Current best block
```

When we're already at the head of the chain (and get new headers immediately) this is not an issue because the tree never gets empty, but when only adding the headers needed for finalization (for example because we're syncing at the moment, I'm not if sure that applies to smoldot-light, too) we're in exactly this situation.

**Comment by tomaka** [comment]
Another option is to attach to each block as "best block score" that is calculated when the block is inserted. Then the best block is simply the block with the highest score. This can normally be implemented in a `O(1)` way.
