### ISSUE TITLE
Smodlot gets panicked on HTTPS

### ISSUE THREAD

**Issue by Douglasacost** [smol-dot/smoldot#794]
Locally over http seems to be working fine, but somehow on https always fail with the following error

```client.js:89 Smoldot has panicked while executing task `connection-12D3KooW9tfcevBR9DjD1JznXY7TenxVoDvtuVKndjgWNizjGUCs-/dns4/node-6975196240558477312-0.p2p.onfinality.io/tcp/25394/ws`. This is a bug in smoldot. Please open an issue at https://github.com/smol-dot/smoldot/issues with the following message:
panicked at 'called `Result::unwrap()` on an `Err` value: "WouldBlock"', wasm-node/rust/src/platform.rs:722:37```

screenshot:
<img width="598" alt="image" src="https://github.com/smol-dot/smoldot/assets/10488928/b4efc3d9-8aed-4991-b080-8bc7522c25c7">

Smoldot v1.0.9

**Comment by tomaka** [comment]
Thanks for the report!

Note that you can by passing the issue by passing `forbidNonLocalWs: true` when calling `start`.
#795 fixes the panic, but the error will still happen afterwards, as it is a browser restriction, and the only way to avoid this error is pass `forbidNonLocalWs: true`, so you probably want to do that anyway.

**Comment by Douglasacost** [comment]
thanks @tomaka ❤️
