### ISSUE TITLE
Smoldot has panicked while executing task `connection-...

### ISSUE THREAD

**Issue by Douglasacost** [smol-dot/smoldot#797]
I'm trying to connect over `wss` nodes ex: `"/dns4/nodle-bootnode-0-tls.p2p.onfinality.io/tcp/443/wss/p2p/12D3KooWMv1jzb45EMGZVGjqgoAjmqPrsYchHCQ13McFKL1r75b5",`, it takes a while and sometimes this errors came out `[connections] Problem during discovery on para_eden_testing_0510: ProtocolNotAvailable`

relay: rococo_v2_2
parachain: nodle tesnet

configuration passed: ```forbidTcp: true,
    forbidNonLocalWs: true,```

screenshot: 
<img width="598" alt="image" src="https://github.com/smol-dot/smoldot/assets/10488928/78489532-9fee-4946-a3d3-46216e37cdab">

possibly related to: https://github.com/smol-dot/smoldot/issues/794

Smoldot v1.0.9

**Comment by tomaka** [comment]
Thanks for the report. I don't test the browser-specific code enough I guess.

`ProtocolNotAvailable` indicates that the bootnodes you're connected to either are of the wrong chain (unlikely) or that their version of Substrate is too old (more likely) and doesn't include https://github.com/paritytech/substrate/pull/12545.

Note that the panic is in no way related to `ProtocolNotAvailable` and I can only fix the panic here.

**Comment by Douglasacost** [comment]
Thanks for the hint @tomaka. Indeed there was some mismatch nodes on my chain-specs 👍
